# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5819f87c8a2d4b1df4f992f6c9c944a9"
application_url = "https://keith-turning-replica-requirements.trycloudflare.com"
embedded = true
name = "StoreHoursManager"
handle = "storehoursmanager"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://keith-turning-replica-requirements.trycloudflare.com/auth/callback",
  "https://keith-turning-replica-requirements.trycloudflare.com/auth/shopify/callback",
  "https://keith-turning-replica-requirements.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://keith-turning-replica-requirements.trycloudflare.com/api/store-hours"
subpath = "store-hours"
prefix = "apps"
